apiVersion: kubernetes.crossplane.io/v1alpha1
kind: Object
metadata:
  name: foo
  annotations:
    kubernetes.crossplane.io/managementType: Undeletable
    argocd.argoproj.io/sync-wave: "3"
spec:
  # Use management policy ObserveDelete to observe or delete k8s resource,
  # but leave to third party to create or update the resource
  forProvider:
    manifest:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: delete-script-waitting
        namespace: katamari
        finalizers:
          - apps/deleting
      spec:
        selector:
          matchLabels:
            app: deleting
        template:
          metadata:
            labels:
              app: deleting
          spec:
            containers:
              - name: deleting
                image: quay.io/openshift/origin-cli:latest
                imagePullPolicy: IfNotPresent
                resources:
                  requests:
                    memory: "500Mi"
                    cpu: "500m"
                  limits:
                    memory: "500Mi"
                    cpu: "500m"
                env:
                  - name: installation_name
                    value: {{.Values.spec.aiManager.instanceName}}
                  - name: installation_namespace
                    value: {{.Values.spec.aiManager.namespace}}
                command:
                  - /bin/sh
                  - -c
                  - |
                    set -x

                    echo "begin"

                    while true; do 
                      status=`oc get Installation $installation_name -n $installation_namespace -o "jsonpath={.metadata.deletionTimestamp}"`
                      if [ "${status}" != "" ]; then
                        echo "deleting........"
                        curl https://codeload.github.com/IBM/cp4waiops-samples/tar.gz/main | tar -xz --strip=2 cp4waiops-samples-main/uninstall
                        cd 3.3
                        ./uninstall-cp4waiops.sh
                        break
                      else
                        sleep 10s
                      fi
                    done

                    oc patch deployment/delete-script-waitting \
                    --type json \
                    --patch='[ { "op": "remove", "path": "/metadata/finalizers" } ]'

                    oc patch clusterrolebinding/ibm-crossplane-provider-kubernetes-operator-4699fdb08852ad \
                    --type json \
                    --patch='[ { "op": "remove", "path": "/metadata/finalizers" } ]'

                    echo "end"
                    sleep 3000s

            restartPolicy: Always
            serviceAccountName: openshift-argocd-admin-deleting
  providerConfigRef:
    name: kubernetes-provider
