apiVersion: kubernetes.crossplane.io/v1alpha1
kind: Object
metadata:
  name: foo
  annotations:
    kubernetes.crossplane.io/managementType: Undeletable
    argocd.argoproj.io/sync-wave: "3"
spec:
  # Use management policy ObserveDelete to observe or delete k8s resource,
  # but leave to third party to create or update the resource
  forProvider:
    manifest:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: delete-script-waitting
        namespace: katamari
        finalizers:
          - apps/deleting
      spec:
        selector:
          matchLabels:
            app: deleting
        template:
          metadata:
            labels:
              app: deleting
          spec:
            containers:
              - name: deleting
                image: quay.io/openshift/origin-cli:latest
                imagePullPolicy: IfNotPresent
                resources:
                  requests:
                    memory: "500Mi"
                    cpu: "500m"
                  limits:
                    memory: "500Mi"
                    cpu: "500m"
                command:
                  - /bin/sh
                  - -c
                  - |
                    set -eo pipefail
                    set -x

                    echo "begin"

                    for ((i=0;i<120;i++))
                    do
                      oc get deployment delete-script-waitting -n katamari
                      sleep 1s
                    done

                    oc patch deployment/delete-script-waitting \
                    --type json \
                    --patch='[ { "op": "remove", "path": "/metadata/finalizers" } ]'

                    oc patch clusterrolebinding/ibm-crossplane-provider-kubernetes-operator-4699fdb08852ad \
                    --type json \
                    --patch='[ { "op": "remove", "path": "/metadata/finalizers" } ]'

                    sleep 3000s

            restartPolicy: Always
            serviceAccountName: openshift-argocd-admin-deleting
  providerConfigRef:
    name: kubernetes-provider
