kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    namespace-scope-configmap: ibm-common-services-namespace-scope
  name: ibm-crossplane-provider-kubernetes-operator-4699fdb08852ad
  namespace: katamari
  finalizers:
    - rbac.authorization.k8s.io/deleting
subjects:
  - kind: ServiceAccount
    name: ibm-crossplane-provider-kubernetes
    namespace: ibm-common-services
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
