apiVersion: kubernetes.crossplane.io/v1alpha1
kind: Object
metadata:
  name: foo-sa
  annotations:
    kubernetes.crossplane.io/managementType: Undeletable
    argocd.argoproj.io/sync-wave: "1"
spec:
  # Use management policy ObserveDelete to observe or delete k8s resource,
  # but leave to third party to create or update the resource
  forProvider:
    manifest:
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: openshift-argocd-admin-deleting
        namespace: katamari
  providerConfigRef:
    name: kubernetes-provider
