---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: openshift-argocd-admin-deleting
  namespace: katamari
  finalizers:
    - apps/deleting
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: openshift-argocd-admin-deleting
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  finalizers:
    - apps/deleting
subjects:
  - kind: ServiceAccount
    name: openshift-argocd-admin-deleting
    namespace: katamari
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
